// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBmuVzjD-NTM3A1ljv4l1IChRge3BJoXA',
    appId: '1:828207111900:web:12a7aa6f0641aff0949e19',
    messagingSenderId: '828207111900',
    projectId: 'homz-application',
    authDomain: 'homz-application.firebaseapp.com',
    storageBucket: 'homz-application.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAruzMsvbcr79B6COzYopJe6fistBcISiM',
    appId: '1:828207111900:android:81b83cc030402260949e19',
    messagingSenderId: '828207111900',
    projectId: 'homz-application',
    storageBucket: 'homz-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYEeszga3l_jaBYd9IS2egOkosLbPSDRs',
    appId: '1:828207111900:ios:f0c2873d24893f93949e19',
    messagingSenderId: '828207111900',
    projectId: 'homz-application',
    storageBucket: 'homz-application.firebasestorage.app',
    iosBundleId: 'com.example.homz',
  );
}
